version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      # - "${NGINX_PUSH_STREAM_PORT}:1935"
    volumes:
      - ./package/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./package/nginx/modules:/etc/nginx/modules/:rw
      - ./package/nginx/php-fpm.d:/etc/nginx/php-fpm.d/:rw
      - ./package/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./package/nginx/ssl:/ssl:rw
      # - ${DATA_DIR}/nginx/rtmp:/tmp/data/rtmp/:rw
      - ${LOGS_DIR}/nginx:/var/log/nginx:rw
      - ${SOURCE_DIR}:/code/:rw

  php-7.4:
    container_name: php-7.4
    build: ./package/php/74
    expose:
      - 9000
    volumes:
      - ./package/php/74/php.ini:/usr/local/etc/php/php.ini:rw
      - ./package/php/74/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:rw
      - ./package/php/74/php-fpm.d:/usr/local/etc/php/php-fpm.d
      - ${SOURCE_DIR}:/code/

  php-8.0:
    container_name: php-8.0
    build: package/php/80
    expose:
      - 9000
    volumes:
      - ./package/php/80/php.ini:/usr/local/etc/php/php.ini:rw
      - ./package/php/80/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:rw
      - ./package/php/80/php-fpm.d:/usr/local/etc/php/php-fpm.d:rw
      - ${SOURCE_DIR}:/code/:rw

  mariadb:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION}
    expose:
      - 3306
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql/:rw
      - ${LOGS_DIR}/mariadb:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    expose:
      - 6379
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./package/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ${DATA_DIR}/redis:/data:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: always
    expose:
      - 5672
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    volumes:
      - ./package/rabbitmq/conf.d:/etc/rabbitmq/conf.d:rw
      - ${LOGS_DIR}/rabbitmq:/var/log/rabbitmq:rw
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq:rw
      - ${DATA_DIR}/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia:rw

  mongodb:
    container_name: mongodb
    image: mongo:${MONGO_VERSION}
    restart: always
    expose:
      - 27017
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${DATA_DIR}/mongo/db:/data/db:rw
      - ${DATA_DIR}/mongo/key:/mongo:rw
      - ${DATA_DIR}/mongo/configdb:/data/configdb:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INNTDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

