version: '3'

services:
  nginx:
    container_name: dnp-nginx
    image: tiangolo/nginx-rtmp:${NGINX_VERSION}
    restart: always
    networks:
      - dnp_environment
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "${NGINX_PUSH_STREAM_PORT}:1935"
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_RTMP_CONF_DIR}:/etc/nginx/rtmp.d/:rw
      - ${NGINX_FASTCGI_PHP_DIR}:/etc/nginx/php-fpm.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_RTMP_RUNTIME}:/tmp/data/rtmp/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx:rw
      - ${SOURCE_DIR}:/code/:rw

  php-fpm:
    container_name: dnp-php-${PHP_VERSION}-fpm
    image: php:${PHP_VERSION}-fpm
    restart: always
    networks:
      - dnp_environment
    expose:
      - 9000
    # command: ['/bin/bash', '/usr/local/etc/php/shell/install-extension.sh']
    volumes:
      # - ./conf/php/shell/install-extension.sh:/usr/local/etc/php/shell/install-extension.sh:rwx
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:rw
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php/php-fpm.conf:rw
      - ${PHP_FPM_CONF_DIR}:/usr/local/etc/php/php-fpm.d:rw
      - ${SUPERVISOR_CONF}:/etc/supervisor/conf.d
      - ${SOURCE_DIR}:/code/:rw

  # php8.2-fpm:
  #   container_name: php8.2-fpm
  #   networks:
  #     - dnp_environment

  mariadb:
    container_name: dnp-mariadb
    image: mariadb:${MARIADB_VERSION}
    restart: always
    networks:
      - dnp_environment
    expose:
      - 3306
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:rw
      - ${DATA_DIR}/mariadb:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"

  redis:
    container_name: dnp-redis
    image: redis:${REDIS_VERSION}
    restart: always
    networks:
      - dnp_environment
    expose:
      - 6379
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.conf:rw
      - ${REDIS_DATA_DIR}:/data/:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    container_name: dnp-rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: always
    networks:
      - dnp_environment
    expose:
      - 5672
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    volumes:
      - ${RABBITMQ_CONFIG_DIR}:/etc/rabbitmq/conf.d/:rw
      - ${RABBITMQ_LOG_DIR}:/var/log/rabbitmq
      - ${RABBITMQ_MNESIA_DIR}:/var/lib/rabbitmq/mnesia

  mongodb:
    container_name: dnp-mongodb
    image: mongo:${MONGO_VERSION}
    restart: always
    networks:
      - dnp_environment
    expose:
      - 27017
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_DATA_DIR}:/data/db:rw
      - ${MONGO_KEY_DATA_DIR}:/mongo:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INNTDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

networks:
  dnp_environment:
    driver: bridge

